### ISSUE TITLE
Problemas de responsividad

### ISSUE THREAD

**Issue by Nidev-lab** [Gonzalof90/3erProyecto_31I#2]
## Proceso

1. Ingrese a la pagina.
2. Hice responsive en mobile en la seccion "Contacto", "Home" y el panel de administrador.

## Resultado esperado

• Que se encuentre todo en condiciones.

## Resultado actual

• Se encuentra un espacio en blanco de manera vertical.

## Captura

![image](https://github.com/Gonzalof90/3erProyecto_31I/assets/53904695/bfd64dd0-8d01-436f-8187-771f97a52511)
![image](https://github.com/Gonzalof90/3erProyecto_31I/assets/53904695/bbbc4a51-700b-45db-b53f-a36f4bd744d4)
![image](https://github.com/Gonzalof90/3erProyecto_31I/assets/53904695/6ba240f6-a237-472d-8add-8d4551c1ca12)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas! Chicos estuve revisando el proyecto y lo unico que queda por revisar seria el responsive en secciones como "Contacto", "Home" y el panel de administrador.

**Comment by Gonzalof90** [comment]
Muchas gracias, ahora lo corregimos

**Comment by Nidev-lab** [comment]
Buenas! Estuve viendo y solo faltaría solucionar el responsive en el panel de administrador y con eso estaríamos.

**Comment by Gonzalof90** [comment]
Buenas, perfecto en eso estamos ahora, ya en un ratito lo subo
