### ISSUE TITLE
Errores de consola

### ISSUE THREAD

**Issue by Nidev-lab** [Gonzalof90/3erProyecto_31I#3]
## Proceso

Ingrese a la pagina.

## Resultado esperado

• Que los productos se encuentren correctamente.

## Resultado actual

•Al ingresar a la pagina se generan errores en las consola y no cargan los productos.

## Captura

![image](https://github.com/Gonzalof90/3erProyecto_31I/assets/53904695/42839158-abce-4990-8ebc-ae8093d32d75)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Gonzalof90** [comment]
Hola Nico , como estás? estoy probando todavía pero no puedo deployarlo, lo
tengo deployado al server, pero el cliente carga pero me aparece como te
sale a vos sin los productos y sin poder loguearme, estoy viendo si puedo
realizarlo, estaba probando en render, me recomendás alguna página donde
poder probar?
